In [202]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [203]:
path = "heart_2022_with_nans.csv"
data=pd.read_csv(path)

In [204]:
data.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,NaN,No,...,NaN,NaN,NaN,No,No,Yes,No,"Yes, received tetanus shot but not sure what type",No,No
1,Alabama,Female,Excellent,0.0,0.0,NaN,No,6.0,NaN,No,...,1.60,68.04,26.57,No,No,No,No,"No, did not receive any tetanus shot in the pa...",No,No
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,Yes,5.0,NaN,No,...,1.57,63.50,25.61,No,No,No,No,NaN,No,Yes
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,NaN,No,...,1.65,63.50,23.30,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,NaN,No,...,1.57,53.98,21.77,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [205]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445132 entries, 0 to 445131
Data columns (total 40 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State                      445132 non-null  object
 1   Sex                        445132 non-null  object
 2   GeneralHealth              443934 non-null  object
 3   PhysicalHealthDays         434205 non-null  float64
 4   MentalHealthDays           436065 non-null  float64
 5   LastCheckupTime            436824 non-null  object
 6   PhysicalActivities         444039 non-null  object
 7   SleepHours                 439679 non-null  float64
 8   RemovedTeeth               433772 non-null  object
 9   HadHeartAttack             442067 non-null  object
 10  HadAngina                  440727 non-null  object
 11  HadStroke                  443575 non-null  object
 12  HadAsthma                  443359 non-null  object
 13  HadSkinCancer              441989 non-null  object
 14  HadCOPD                    442913 non-null  object
 15  HadDepressiveDisorder      442320 non-null  object
 16  HadKidneyDisease           443206 non-null  object
 17  HadArthritis               442499 non-null  object
 18  HadDiabetes                444045 non-null  object
 19  DeafOrHardOfHearing        424485 non-null  object
 20  BlindOrVisionDifficulty    423568 non-null  object
 21  DifficultyConcentrating    420892 non-null  object
 22  DifficultyWalking          421120 non-null  object
 23  DifficultyDressingBathing  421217 non-null  object
 24  DifficultyErrands          419476 non-null  object
 25  SmokerStatus               409670 non-null  object
 26  ECigaretteUsage            409472 non-null  object
 27  ChestScan                  389086 non-null  object
 28  RaceEthnicityCategory      431075 non-null  object
 29  AgeCategory                436053 non-null  object
 30  HeightInMeters             416480 non-null  float64
 31  WeightInKilograms          403054 non-null  float64
 32  BMI                        396326 non-null  float64
 33  AlcoholDrinkers            398558 non-null  object
 34  HIVTesting                 379005 non-null  object
 35  FluVaxLast12               398011 non-null  object
 36  PneumoVaxEver              368092 non-null  object
 37  TetanusLast10Tdap          362616 non-null  object
 38  HighRiskLastYear           394509 non-null  object
 39  CovidPos                   394368 non-null  object
dtypes: float64(6), object(34)
memory usage: 135.8+ MB

In [206]:
data.drop(['RemovedTeeth'],axis =1, inplace=True)

In [207]:
data.drop(['HadSkinCancer'],axis =1, inplace=True)

In [208]:
data.drop(['DeafOrHardOfHearing'],axis =1, inplace=True)

In [209]:
data.drop(['BlindOrVisionDifficulty'],axis =1, inplace=True)

In [210]:
data.drop(['DifficultyConcentrating'],axis =1, inplace=True)

In [211]:
data.drop(['DifficultyDressingBathing'],axis =1, inplace=True)

In [212]:
data.drop(['HeightInMeters'],axis =1, inplace=True)

In [213]:
data.drop(['HadCOPD'],axis =1, inplace=True)

In [214]:
data.drop(['HadAsthma'],axis =1, inplace=True)

In [305]:
data.drop(['HadKidneyDisease'],axis =1, inplace=True)

In [215]:
data.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,...,AgeCategory,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,No,No,...,Age 80 or older,NaN,NaN,No,No,Yes,No,"Yes, received tetanus shot but not sure what type",No,No
1,Alabama,Female,Excellent,0.0,0.0,NaN,No,6.0,No,No,...,Age 80 or older,68.04,26.57,No,No,No,No,"No, did not receive any tetanus shot in the pa...",No,No
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,Yes,5.0,No,No,...,Age 55 to 59,63.50,25.61,No,No,No,No,NaN,No,Yes
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,No,No,...,NaN,63.50,23.30,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,No,No,...,Age 40 to 44,53.98,21.77,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [216]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445132 entries, 0 to 445131
Data columns (total 31 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   State                  445132 non-null  object
 1   Sex                    445132 non-null  object
 2   GeneralHealth          443934 non-null  object
 3   PhysicalHealthDays     434205 non-null  float64
 4   MentalHealthDays       436065 non-null  float64
 5   LastCheckupTime        436824 non-null  object
 6   PhysicalActivities     444039 non-null  object
 7   SleepHours             439679 non-null  float64
 8   HadHeartAttack         442067 non-null  object
 9   HadAngina              440727 non-null  object
 10  HadStroke              443575 non-null  object
 11  HadDepressiveDisorder  442320 non-null  object
 12  HadKidneyDisease       443206 non-null  object
 13  HadArthritis           442499 non-null  object
 14  HadDiabetes            444045 non-null  object
 15  DifficultyWalking      421120 non-null  object
 16  DifficultyErrands      419476 non-null  object
 17  SmokerStatus           409670 non-null  object
 18  ECigaretteUsage        409472 non-null  object
 19  ChestScan              389086 non-null  object
 20  RaceEthnicityCategory  431075 non-null  object
 21  AgeCategory            436053 non-null  object
 22  WeightInKilograms      403054 non-null  float64
 23  BMI                    396326 non-null  float64
 24  AlcoholDrinkers        398558 non-null  object
 25  HIVTesting             379005 non-null  object
 26  FluVaxLast12           398011 non-null  object
 27  PneumoVaxEver          368092 non-null  object
 28  TetanusLast10Tdap      362616 non-null  object
 29  HighRiskLastYear       394509 non-null  object
 30  CovidPos               394368 non-null  object
dtypes: float64(5), object(26)
memory usage: 105.3+ MB

In [217]:
data.isna().sum()

State                        0
Sex                          0
GeneralHealth             1198
PhysicalHealthDays       10927
MentalHealthDays          9067
LastCheckupTime           8308
PhysicalActivities        1093
SleepHours                5453
HadHeartAttack            3065
HadAngina                 4405
HadStroke                 1557
HadDepressiveDisorder     2812
HadKidneyDisease          1926
HadArthritis              2633
HadDiabetes               1087
DifficultyWalking        24012
DifficultyErrands        25656
SmokerStatus             35462
ECigaretteUsage          35660
ChestScan                56046
RaceEthnicityCategory    14057
AgeCategory               9079
WeightInKilograms        42078
BMI                      48806
AlcoholDrinkers          46574
HIVTesting               66127
FluVaxLast12             47121
PneumoVaxEver            77040
TetanusLast10Tdap        82516
HighRiskLastYear         50623
CovidPos                 50764
dtype: int64

In [218]:
data['PhysicalActivities'] = data['PhysicalActivities'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

C:\Users\taher\AppData\Local\Temp\ipykernel_8724\1715346369.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['PhysicalActivities'] = data['PhysicalActivities'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [219]:
data.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,...,AgeCategory,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,0.0,8.0,No,No,...,Age 80 or older,NaN,NaN,No,No,Yes,No,"Yes, received tetanus shot but not sure what type",No,No
1,Alabama,Female,Excellent,0.0,0.0,NaN,0.0,6.0,No,No,...,Age 80 or older,68.04,26.57,No,No,No,No,"No, did not receive any tetanus shot in the pa...",No,No
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,1.0,5.0,No,No,...,Age 55 to 59,63.50,25.61,No,No,No,No,NaN,No,Yes
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,1.0,7.0,No,No,...,NaN,63.50,23.30,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,1.0,9.0,No,No,...,Age 40 to 44,53.98,21.77,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [220]:
data['HadHeartAttack'] = data['HadHeartAttack'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

C:\Users\taher\AppData\Local\Temp\ipykernel_8724\1740652218.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['HadHeartAttack'] = data['HadHeartAttack'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [221]:
data.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,...,AgeCategory,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,0.0,8.0,0.0,No,...,Age 80 or older,NaN,NaN,No,No,Yes,No,"Yes, received tetanus shot but not sure what type",No,No
1,Alabama,Female,Excellent,0.0,0.0,NaN,0.0,6.0,0.0,No,...,Age 80 or older,68.04,26.57,No,No,No,No,"No, did not receive any tetanus shot in the pa...",No,No
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,1.0,5.0,0.0,No,...,Age 55 to 59,63.50,25.61,No,No,No,No,NaN,No,Yes
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,1.0,7.0,0.0,No,...,NaN,63.50,23.30,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,1.0,9.0,0.0,No,...,Age 40 to 44,53.98,21.77,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [222]:
data['AlcoholDrinkers'] = data['AlcoholDrinkers'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

C:\Users\taher\AppData\Local\Temp\ipykernel_8724\1510741982.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['AlcoholDrinkers'] = data['AlcoholDrinkers'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [223]:
data.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,...,AgeCategory,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,0.0,8.0,0.0,No,...,Age 80 or older,NaN,NaN,0.0,No,Yes,No,"Yes, received tetanus shot but not sure what type",No,No
1,Alabama,Female,Excellent,0.0,0.0,NaN,0.0,6.0,0.0,No,...,Age 80 or older,68.04,26.57,0.0,No,No,No,"No, did not receive any tetanus shot in the pa...",No,No
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,1.0,5.0,0.0,No,...,Age 55 to 59,63.50,25.61,0.0,No,No,No,NaN,No,Yes
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,1.0,7.0,0.0,No,...,NaN,63.50,23.30,0.0,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,1.0,9.0,0.0,No,...,Age 40 to 44,53.98,21.77,1.0,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [224]:
data['HIVTesting'] = data['HIVTesting'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

C:\Users\taher\AppData\Local\Temp\ipykernel_8724\741234820.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['HIVTesting'] = data['HIVTesting'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [225]:
data.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,...,AgeCategory,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,0.0,8.0,0.0,No,...,Age 80 or older,NaN,NaN,0.0,0.0,Yes,No,"Yes, received tetanus shot but not sure what type",No,No
1,Alabama,Female,Excellent,0.0,0.0,NaN,0.0,6.0,0.0,No,...,Age 80 or older,68.04,26.57,0.0,0.0,No,No,"No, did not receive any tetanus shot in the pa...",No,No
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,1.0,5.0,0.0,No,...,Age 55 to 59,63.50,25.61,0.0,0.0,No,No,NaN,No,Yes
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,1.0,7.0,0.0,No,...,NaN,63.50,23.30,0.0,0.0,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,1.0,9.0,0.0,No,...,Age 40 to 44,53.98,21.77,1.0,0.0,No,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [226]:
data['FluVaxLast12'] = data['FluVaxLast12'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

C:\Users\taher\AppData\Local\Temp\ipykernel_8724\147868610.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['FluVaxLast12'] = data['FluVaxLast12'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [227]:
data.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,...,AgeCategory,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,0.0,8.0,0.0,No,...,Age 80 or older,NaN,NaN,0.0,0.0,1.0,No,"Yes, received tetanus shot but not sure what type",No,No
1,Alabama,Female,Excellent,0.0,0.0,NaN,0.0,6.0,0.0,No,...,Age 80 or older,68.04,26.57,0.0,0.0,0.0,No,"No, did not receive any tetanus shot in the pa...",No,No
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,1.0,5.0,0.0,No,...,Age 55 to 59,63.50,25.61,0.0,0.0,0.0,No,NaN,No,Yes
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,1.0,7.0,0.0,No,...,NaN,63.50,23.30,0.0,0.0,1.0,Yes,"No, did not receive any tetanus shot in the pa...",No,No
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,1.0,9.0,0.0,No,...,Age 40 to 44,53.98,21.77,1.0,0.0,0.0,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [228]:
data['PneumoVaxEver'] = data['PneumoVaxEver'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

C:\Users\taher\AppData\Local\Temp\ipykernel_8724\1024119701.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['PneumoVaxEver'] = data['PneumoVaxEver'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [229]:
data.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,...,AgeCategory,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,0.0,8.0,0.0,No,...,Age 80 or older,NaN,NaN,0.0,0.0,1.0,0.0,"Yes, received tetanus shot but not sure what type",No,No
1,Alabama,Female,Excellent,0.0,0.0,NaN,0.0,6.0,0.0,No,...,Age 80 or older,68.04,26.57,0.0,0.0,0.0,0.0,"No, did not receive any tetanus shot in the pa...",No,No
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,1.0,5.0,0.0,No,...,Age 55 to 59,63.50,25.61,0.0,0.0,0.0,0.0,NaN,No,Yes
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,1.0,7.0,0.0,No,...,NaN,63.50,23.30,0.0,0.0,1.0,1.0,"No, did not receive any tetanus shot in the pa...",No,No
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,1.0,9.0,0.0,No,...,Age 40 to 44,53.98,21.77,1.0,0.0,0.0,1.0,"No, did not receive any tetanus shot in the pa...",No,No

In [230]:
data['HighRiskLastYear'] = data['HighRiskLastYear'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

C:\Users\taher\AppData\Local\Temp\ipykernel_8724\2089131881.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['HighRiskLastYear'] = data['HighRiskLastYear'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [231]:
data['CovidPos'] = data['CovidPos'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [232]:
data['HadAngina'] = data['HadAngina'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

C:\Users\taher\AppData\Local\Temp\ipykernel_8724\3929659617.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['HadAngina'] = data['HadAngina'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [233]:
data.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,...,AgeCategory,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,0.0,8.0,0.0,0.0,...,Age 80 or older,NaN,NaN,0.0,0.0,1.0,0.0,"Yes, received tetanus shot but not sure what type",0.0,0
1,Alabama,Female,Excellent,0.0,0.0,NaN,0.0,6.0,0.0,0.0,...,Age 80 or older,68.04,26.57,0.0,0.0,0.0,0.0,"No, did not receive any tetanus shot in the pa...",0.0,0
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,1.0,5.0,0.0,0.0,...,Age 55 to 59,63.50,25.61,0.0,0.0,0.0,0.0,NaN,0.0,1
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,1.0,7.0,0.0,0.0,...,NaN,63.50,23.30,0.0,0.0,1.0,1.0,"No, did not receive any tetanus shot in the pa...",0.0,0
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,1.0,9.0,0.0,0.0,...,Age 40 to 44,53.98,21.77,1.0,0.0,0.0,1.0,"No, did not receive any tetanus shot in the pa...",0.0,0

In [234]:
data['HadStroke'] = data['HadStroke'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

C:\Users\taher\AppData\Local\Temp\ipykernel_8724\3859315341.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['HadStroke'] = data['HadStroke'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [235]:
data['HadDepressiveDisorder'] = data['HadDepressiveDisorder'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

C:\Users\taher\AppData\Local\Temp\ipykernel_8724\2403785628.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['HadDepressiveDisorder'] = data['HadDepressiveDisorder'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [236]:
data['HadArthritis'] = data['HadArthritis'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

C:\Users\taher\AppData\Local\Temp\ipykernel_8724\3359622431.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['HadArthritis'] = data['HadArthritis'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [237]:
data['HadDiabetes'] = data['HadDiabetes'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [238]:
data['DifficultyWalking'] = data['DifficultyWalking'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

C:\Users\taher\AppData\Local\Temp\ipykernel_8724\2623912818.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['DifficultyWalking'] = data['DifficultyWalking'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [239]:
data['ChestScan'] = data['ChestScan'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

C:\Users\taher\AppData\Local\Temp\ipykernel_8724\3874703619.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['ChestScan'] = data['ChestScan'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [240]:
data['AlcoholDrinkers'] = data['AlcoholDrinkers'].replace({'Yes': 1, 'No': 0}).infer_objects(copy=False)

In [241]:
data.drop(['DifficultyErrands'],axis =1, inplace=True)

In [242]:
data.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,...,AgeCategory,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,0.0,8.0,0.0,0.0,...,Age 80 or older,NaN,NaN,0.0,0.0,1.0,0.0,"Yes, received tetanus shot but not sure what type",0.0,0
1,Alabama,Female,Excellent,0.0,0.0,NaN,0.0,6.0,0.0,0.0,...,Age 80 or older,68.04,26.57,0.0,0.0,0.0,0.0,"No, did not receive any tetanus shot in the pa...",0.0,0
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,1.0,5.0,0.0,0.0,...,Age 55 to 59,63.50,25.61,0.0,0.0,0.0,0.0,NaN,0.0,1
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,1.0,7.0,0.0,0.0,...,NaN,63.50,23.30,0.0,0.0,1.0,1.0,"No, did not receive any tetanus shot in the pa...",0.0,0
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,1.0,9.0,0.0,0.0,...,Age 40 to 44,53.98,21.77,1.0,0.0,0.0,1.0,"No, did not receive any tetanus shot in the pa...",0.0,0

In [243]:
data.to_csv('exported_heart_data.csv', index=False)

In [289]:
# handling the values of somkers :
#'Never smoked': 0
#'Former smoker': 0.25
#'Current smoker - now smokes some days':0.75
#'Current smoker - now smokes every day':1
data['SmokerStatus'] = data['SmokerStatus'].replace({'Never smoked': 0, 'Former smoker': 0.25, 'Current smoker - now smokes some days':0.75, 'Current smoker - now smokes every day':1}).infer_objects(copy=False)

In [291]:
data.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,...,AgeCategory,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,0.0,8.0,0.0,0.0,...,Age 80 or older,NaN,NaN,0.0,0.0,1.0,0.0,"Yes, received tetanus shot but not sure what type",0.0,0
1,Alabama,Female,Excellent,0.0,0.0,NaN,0.0,6.0,0.0,0.0,...,Age 80 or older,68.04,26.57,0.0,0.0,0.0,0.0,"No, did not receive any tetanus shot in the pa...",0.0,0
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,1.0,5.0,0.0,0.0,...,Age 55 to 59,63.50,25.61,0.0,0.0,0.0,0.0,NaN,0.0,1
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,1.0,7.0,0.0,0.0,...,NaN,63.50,23.30,0.0,0.0,1.0,1.0,"No, did not receive any tetanus shot in the pa...",0.0,0
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,1.0,9.0,0.0,0.0,...,Age 40 to 44,53.98,21.77,1.0,0.0,0.0,1.0,"No, did not receive any tetanus shot in the pa...",0.0,0

In [295]:
data['SmokerStatus']

0         0.00
1         0.00
2         0.00
3         0.75
4         0.00
          ...
445127    0.00
445128    0.00
445129    1.00
445130    0.00
445131    0.25
Name: SmokerStatus, Length: 445132, dtype: float64

In [309]:
# handling the values of somkers:
#'Never used e-cigarettes in my entire life': 0
#'Not at all (right now)':0.25
#'Use them some days':0.75
#'Use them every day':1
data['ECigaretteUsage'] = data['ECigaretteUsage'].replace({'Never used e-cigarettes in my entire life': 0, 'Not at all (right now)':0.25,'Use them some days':0.75 ,'Use them every day':1}).infer_objects(copy=False)

C:\Users\taher\AppData\Local\Temp\ipykernel_8724\4133435871.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['ECigaretteUsage'] = data['ECigaretteUsage'].replace({'Never used e-cigarettes in my entire life': 0, 'Not at all (right now)':0.25,'Use them some days':0.75 ,'Use them every day':1}).infer_objects(copy=False)

In [319]:
# handling the values of somkers:
#'Never used e-cigarettes in my entire life': 0
#'Not at all (right now)':0.25
#'Use them some days':0.75
#'Use them every day':1
data['ECigaretteUsage'] = data['ECigaretteUsage'].replace({'Never used e-cigarettes in my entire life': 0, 'Not at all (right now)':0.25,'Use them some days':0.75 ,'Use them every day':1}).infer_objects(copy=False)

In [321]:
data['ECigaretteUsage']

0         0.50
1         0.00
2         0.00
3         0.00
4         0.00
          ...
445127    0.00
445128    0.00
445129    0.75
445130    0.00
445131    0.50
Name: ECigaretteUsage, Length: 445132, dtype: float64

In [315]:
data.to_csv('exported_heart_data.csv', index=False)